source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

target 'ShopApp' do
  pod 'Lynx', '3.6.0', :subspecs => [
    'Framework',
  ]

  pod 'LynxService', '3.6.0', :subspecs => [
    'Image',
    'Log',
    'Http',
  ]

  pod 'SDWebImage', '5.15.5'
  pod 'SDWebImageWebPCoder', '0.11.0'

  pod 'XElement', '3.6.0'
end
